version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - OPENFGA_API_URL=http://openfga:8081
      - OPENFGA_API_KEY=your_openfga_api_key
      - OPENFGA_AUTH_MODEL_ID=your_model_id_here
    depends_on:
      - postgres
      - openfga

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: your_database
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  openfga:
    image: openfga/openfga:latest
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: postgres://your_user:your_password@postgres/your_database?sslmode=disable
      # Set other necessary OpenFGA environment variables here

volumes:
  postgres_data:
